services:
  - type: web
    name: entrepedia-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.api.main:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres:Glory2GodAlways2023!@db.apmwojsfejoiugiohipm.supabase.co:5432/postgres
      - key: SUPABASE_URL
        value: https://apmwojsfejoiugiohipm.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbXdvanNmZWpvaXVnaW9oaXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0Mzc2MDEsImV4cCI6MjA4MDAxMzYwMX0.aJdRDnyKgLNyyvAxPBH-HRDA6yL1zk7p5EFaF4ju5AM
      - key: STORAGE_TYPE
        value: supabase
      - key: VECTOR_DB_TYPE
        value: supabase
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        value: AIzaSyCpJ7QG7rSsWKPalelbHKZ-hLZK8pMPNQ8
      - key: ANTHROPIC_API_KEY
        sync: false
